//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sigma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User() { }
        public User(int id)
        {
            Id = id;
            Name = "Jane Keptton";
            AvatarUrl = "/Content/img/avatars/avatar0.jpg";
            Position = "senior .Net programmer";
        }
        public void ChangeData(string UserName, string UserPosition, string UserAbout)
        {
            Name = UserName;
            Position = UserPosition;
            About = UserAbout;
        }
        public int Id { get; set; }
        public string Name { get; set; }
        public string AvatarUrl { get; set; }
        public string Position { get; set; }
        public string About { get; set; }
    }
}
